package com.election.backend.mapper;

import com.election.backend.dto.CreateUserRequestDto;
import com.election.backend.dto.UpdateUserRequestDto;
import com.election.backend.dto.UserDto;
import com.election.backend.model.AppUser;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface UserMapper {

    UserDto toDto(AppUser user);

    AppUser toEntity(UserDto userDto);


    @Mapping(target = "id", ignore = true)       // ID is auto-generated by DB
    @Mapping(target = "password", ignore = true) // Ignore plain password; we set the hash manually
    @Mapping(target = "role", defaultValue = "ROLE_USER") // Handle the default role logic here
    AppUser createRequestToEntity(CreateUserRequestDto request);

    void updateEntityFromRequest(UpdateUserRequestDto request, @MappingTarget AppUser user);
}